//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.PatentApplicationSystem.办案员.客户指示办案 {
    
    
    public partial class 客户指示办案 {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Homework.PatentApplicationSystem.CaseHandleMaster Master {
            get {
                return ((Homework.PatentApplicationSystem.CaseHandleMaster)(base.Master));
            }
        }
    }
}
