//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.PatentApplicationSystem.代理部主管.代理部内审 {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Homework.PatentApplicationSystem.CaseListMaster Master {
            get {
                return ((Homework.PatentApplicationSystem.CaseListMaster)(base.Master));
            }
        }
    }
}
